[tool.poetry]
name = "yacv-server"
version = "0.1.0"
description = "Yet Another CAD Viewer (server)"
authors = ["Yeicor <4929005+Yeicor@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

# CAD
build123d = "^0.3.0"

# Web
aiohttp = "^3.9.3"
aiohttp-devtools = "^1.1.2"

# Misc
pygltflib = "^1.16.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
