name: "maybe deploy"

on:
  push:
    tags:
      - "v**"


permissions:
  contents: "write"

jobs:
  deploy:
    concurrency: "ci-${{ github.ref }}" # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: "ubuntu-latest"
    steps:
      - uses: "dawidd6/action-download-artifact@v3"
        with:
          workflow: "build"
          name: "frontend"
          path: "./public"
      - uses: "dawidd6/action-download-artifact@v3"
        with:
          workflow: "build"
          name: "logo"
          path: "./public"
      - run: "ls -l -R ./public"
      - uses: "JamesIves/github-pages-deploy-action@v4"
        with:
          folder: "public"
      - uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: "./public/*"
          asset_name: "frontend"
          tag: "${{ github.ref }}"
          overwrite: true
          file_glob: true

