name: "Deploy"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: "write"

jobs:
  build-and-deploy:
    concurrency: "ci-${{ github.ref }}" # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/download-artifact@v4"
        with:
          name: "frontend"
          path: "./public"
      - uses: "actions/download-artifact@v4"
        with:
          name: "logo"
          path: "./public"
      - run: "ls -l -R ./public"
      - uses: "JamesIves/github-pages-deploy-action@v4"
        with:
          folder: "public"

