name: "Deploy"

on:
  workflow_run:
    workflows: ["ci.yml"]
    types:
      - "completed"


permissions:
  contents: "write"

jobs:
  check-early-exit:
    runs-on: "ubuntu-latest"
    outputs:
      should_deploy: "${{ steps.check-early-exit.outputs.should_deploy }}"
    steps:
      - run: "echo ${{ github.ref }}"
      - run: "echo ${{ github.ref }} | grep -q -v -E '^refs/tags/v[0-9]+\\.[0-9]+\\.[0-9]+$' && echo '::set-output name=should_deploy::false' || echo '::set-output name=should_deploy::true'"
  deploy:
    concurrency: "ci-${{ github.ref }}" # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: "ubuntu-latest"
    needs: "check-early-exit"
    if: "needs.check-early-exit.outputs.should_deploy == 'true'"
    steps:
      - uses: "dawidd6/action-download-artifact@v3"
        with:
          workflow: "ci.yml"
          name: "frontend"
          path: "./public"
      - uses: "dawidd6/action-download-artifact@v3"
        with:
          workflow: "ci.yml"
          name: "logo"
          path: "./public"
      - run: "ls -l -R ./public"
      - uses: "JamesIves/github-pages-deploy-action@v4"
        with:
          folder: "public"
      - uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: "./public/*"
          asset_name: "frontend"
          tag: "${{ github.ref }}"
          overwrite: true
          file_glob: true

