on:
  push:
    tags:
      - "v**"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: "write"
  pages: "write"
  id-token: "write"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-frontend:
    runs-on: "ubuntu-latest"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - uses: "dawidd6/action-download-artifact@v3"
        with:
          workflow: "build.yml"
          name: "frontend"
          path: "./public"
          allow_forks: false
      - uses: "dawidd6/action-download-artifact@v3"
        with:
          workflow: "build.yml"
          name: "logo"
          path: "./public"
          allow_forks: false
      - uses: "actions/configure-pages@v4"
      - uses: "actions/upload-pages-artifact@v3"
        with:
          path: 'public'
      - id: "deployment"
        uses: "actions/deploy-pages@v4"
      - run: 'zip -r frontend.zip public'
      - uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: "frontend.zip"
          tag: "${{ github.ref }}"
          overwrite: true

  # TODO: deploy-backend
